### ISSUE TITLE
TLS/SSL works only for Firefox

### ISSUE THREAD

**Issue by berendt** [osism/testbed#1166]
```
Feedback for new SSL/TLS implementation: Firefox works, but Safari and
Chrome refuses to work with selfsigned wildcard certs. A hint would be
helpful how to make those browsers work with testbed. Those issues are
quite kinda frustrating if things do not work at all after a deployment.
```

Split from #1162

**Comment by berendt** [comment]
I cannot reproduce this myself at the moment. At least Chrome works here without problems.

**Comment by berendt** [comment]
@ amachowiak You imported the used CA?

**Comment by amachowiak** [comment]
No.

I read https://docs.osism.tech/testbed/deployment.html#tls-certificates-and-hostnames and wasnt sure what to do to fix the issue.
Options: 
* Search for the wildcard certificate and import/trust it
* Search for CA cert and import/trust it

Also, I am wondering: Is the CA fixed and do I re-use the same identical CA key/cert pair for all (future) testbed deployments and the cert just needs to be imported once? Or does testbed create a new CA key/cert pair on each new deployment and do I have to re-import it every time I create a new testbed?

Would be helpful to get some guidance here in the docs.

**Comment by berendt** [comment]
The CA is fixed in the testbed and is not planned to change for the next 10 years. I'll make a note of that in the documentation.

So if you import this CA it should work. Can you test this?

**Comment by amachowiak** [comment]
I imported manager:/opt/configuration/environments/kolla/certificates/ca/testbed.crt to my Mac OSX key-chain "system". However, 
https://api.testbed.osism.xyz is still broken ("NET::ERR_CERT_INVALID") in Chrome.

**Comment by berendt** [comment]
I'm deploying the Identity Testbed right now and then I'll go through all the issues at my own leisure during the day. Remove then also times here the imported CA on MacOS.
